### PR TITLE
html file handling

### PR DESCRIPTION
**Pull request by sdp5**
[ZNTA-1089](https://zanata.atlassian.net/browse/ZNTA-1089) - Improve html handling from Drupal plugin

Work In Progress.
- [x] html file push [example](https://translate.zanata.org/webtrans/Application.seam?project=88888&iteration=drupal1&localeId=hi&locale=en#view:doc;doc:node/26/Downloads.Body.html)
- [x] html file pull
- [x] code refactor
- [x] statistics api `translations threshold`
- [x] formats compatibility `html`, `plain_text`
- [x] handle custom node fields
- [x] code cleanup
- [x] rhel6 test

---

This change is [Reviewable](https://reviewable.io/reviews/sundeep-co-in/tmgmt_zanata/2)

### CODE REVIEW

**Comment by sdp5** [comment]
@davidmason Please have a look..

**Comment by davidmason** [comment]
Reviewed 1 of 6 files at r1, 1 of 3 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

_[tmgmt_zanata.connector.inc, line 71 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIz3-16GyYC0fM795Pa:-KIz3-17iWr_FvmegyY8:-17831552) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L71)):_

> ``` SourcePawn
>     $count_strings_changed = 0;
>     $response = null;
>     $entire_translations= null;
> ```

add space before `=`

---

_[tmgmt_zanata.connector.inc, line 123 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzCAHgEJv8JbdU4EN3:-KIzCAHgEJv8JbdU4EN4:1967868907) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L123)):_

> ``` SourcePawn
>         foreach ($non_html_docs as $index => $doc) {
>           if ($doc == $docId) {
>             $url = $url = $this->restclient->getItemTranslationUrl($job_item);
> ```

has `$url =` twice

---

_[tmgmt_zanata.connector.inc, line 147 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzD1z_z2HIEcew_QRi:-KIzD1z_z2HIEcew_QRj:-1888014435) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L147)):_

> ``` SourcePawn
>             $response = $this->restclient->process_request($url, $options, true);
>             // FIXME 'body][0][value' (suffice as of now)
>             $html_docs_translations[$doc] = $this->createItemResponse('body][0][value', $response->data);
> ```

Does this mean that only something with the name of exactly `body][0][value` can be translated as HTML? If so, it may fail for some customer portal nodes since they use some fields other than `body` for the main content.

---

_[tmgmt_zanata.connector.inc, line 151 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzDVrEO-cOimgGoNBD:-KIzDVrEO-cOimgGoNBE:572568567) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L151)):_

> ``` SourcePawn
>         }
> 
>         // club all the translations received from server
> ```

It looks like this should say "combine all the translations..." or "merge all the translations..."

---

_[tmgmt_zanata.connector.inc, line 680 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIz6mOZf3Z82ypINZe-:-KIz6mOZf3Z82ypINZe0:-2002138536) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L680)):_

> ``` SourcePawn
>     // check and set html flag
>     $html_segmentation_setting =
>         $this->translator->getSetting('segmentation') === 'HTML';
> ```

If this is `FALSE`, there is no need to check anything else, so it could be replaced with:

``` php
if ($this->translator->getSetting('segmentation') !== 'HTML') {
  return FALSE;
}
```

---

_[tmgmt_zanata.connector.inc, line 684 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzEWoKdYKBao4c-fCY:-KIzEWoL8HNICy5f0lrp:-1793431311) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L684)):_

> ``` SourcePawn
>     $job_data = $job_item->data;
>     foreach ($job_data as $node_field => $value_array) {
>       if ($node_field === 'body') {
> ```

What happens when there is a html content field that is not called 'body'?

---

_[tmgmt_zanata.connector.inc, line 688 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIz5ne8b3H3Nn7NbSdD:-KIz5ne9QBrExPpsCbqr:1683417430) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L688)):_

> ``` SourcePawn
>           if (is_int($field)) {
>             $node_content_format = $contents['format']['#text'];
>             $html_content = strstr($node_content_format, 'html');
> ```

I think this loop could exit early when it finds a `html` content format since there is no need to check anything else. Assuming the previous recommendation is used, it would be something like:

``` php
if (strstr($node_content_format, 'html')) {
  return TRUE;
}
```

The final return from the function would just be `return FALSE;`

---

_[tmgmt_zanata.connector.inc, line 757 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIz99pQsVytwua4N3-X:-KIz99pRXYimejqsnHFd:106446384) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L757)):_

> ``` SourcePawn
>           $process_request_queue[$url] =  $options;
> 
>         }
> ```

It looks like this code will only process `'node_title'` and `'Body'`. Is this right?

We want to process all translatable fields in a node, which may be custom fields, so this may need a final `else` clause to process any other fields so that they are in the same document as the node title (the node title should always be first).

Will this handle the case where there is a HTML content field that is not labeled 'Body'? We may need to check for HTML content type for each field instead of just checking Body.

---

_[tmgmt_zanata.connector.inc, line 766 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzPJO0i1r8N2ZtJPWq:-KIzPJO0i1r8N2ZtJPWr:311186097) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L766)):_

> ``` SourcePawn
>     $response = null;
>     foreach ($process_request_queue as $url => $options) {
>       $response = $this->restclient->process_request($url, $options);
> ```

This will lose the `$response` if multiple requests are sent, so we will not be able to tell if one of the earlier requests failed. We should capture them in an array and check that they all succeeded.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2)_

**Comment by davidmason** [comment]
To test this, we need to add a custom field to a node type in Drupal and make sure it can be translated as HTML as well. For reference, look at the original html document that we were having trouble with on customer portal - I think that uses a field other than Body for its content.

<details><summary>

<i>Previously, sundeep-co-in (Sundeep Anand) wrote…</i></summary>



> @davidmason Please have a look..
> </details>

---

Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-:-KIzR6bDf0z6tgWOkljP:-1174077208)_

**Comment by sdp5** [comment]
@davidmason thanks for the inputs, you may please resume.

<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> To test this, we need to add a custom field to a node type in Drupal and make sure it can be translated as HTML as well. For reference, look at the original html document that we were having trouble with on customer portal - I think that uses a field other than Body for its content.
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-:-KJ1LkfRcZX_JFxSpfSv:1442984646)_

**Comment by sdp5** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

_[tmgmt_zanata.connector.inc, line 684 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzEWoKdYKBao4c-fCY:-KJ4K4ELPi6okZPPm7Jq:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L684)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> What happens when there is a html content field that is not called 'body'?
> </details>
> Done.

---

_[tmgmt_zanata.connector.inc, line 757 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIz99pQsVytwua4N3-X:-KJ4KH5qTEOhuBgnONd1:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L757)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> It looks like this code will only process `'node_title'` and `'Body'`. Is this right?
> 
> We want to process all translatable fields in a node, which may be custom fields, so this may need a final `else` clause to process any other fields so that they are in the same document as the node title (the node title should always be first).
> 
> Will this handle the case where there is a HTML content field that is not labeled 'Body'? We may need to check for HTML content type for each field instead of just checking Body.
> </details>
> Done.

---

_[tmgmt_zanata.connector.inc, line 766 [r2]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KIzPJO0i1r8N2ZtJPWq:-KJ4KIBVg5YbYiFRBkq-:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/0807d823e61994ea134a45dac55d2a97f3bc29dc/tmgmt_zanata.connector.inc#L766)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> This will lose the `$response` if multiple requests are sent, so we will not be able to tell if one of the earlier requests failed. We should capture them in an array and check that they all succeeded.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2)_

**Comment by davidmason** [comment]
Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 3 of 4 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

_[tmgmt_zanata.connector.inc, line 770 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4LPPiNPBvzDjj5KRH:-KJ4LPPiNPBvzDjj5KRI:1244668107) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.connector.inc#L770)):_

> ``` SourcePawn
>     }
> 
>     function test_response_code($response){
> ```

I suggest the name `not_success_response` to be more obvious what it does.

---

_[tmgmt_zanata.connector.inc, line 777 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4MD2Mxz4dBt0trvYS:-KJ4MD2Mxz4dBt0trvYT:38075056) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.connector.inc#L777)):_

> ``` SourcePawn
>       foreach ($responses as $resp) {
>         if (!in_array($resp->code, array(200, 201))) {
>           $response = $resp;
> ```

This will still only report on one of the response codes. It will be better if we can generate a message or multiple messages that say what was successful and what failed.

For example, if there is a document that has a success response for the non-html parts but a failure response when it sends "Body" as a html document, there could be 2 messages:

``` php
$job_item->addMessage(
          'Sent document: non-html strings for item "@title" sent to Zanata as document "@doc_id".',
          array(...));

$job_item->addMessage(
          'Html content "@fieldname" for item "@title" was not successfully sent to Zanata due to ...',
          array(...), 'error');
```

The message depends on the type of error, like in the current switch statement. The switch statement below could be used if it is included inside a loop over the responses. The return statements would need to be removed, and at the end of the function just return true if all are success (maybe with `return !empty(array_filter($responses, 'test_response_code'));`)

---

_[tmgmt_zanata.utils.inc, line 82 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4FSLhuQMy6ownUTC9:-KJ4FSLiqVVUpn3AUJDw:1080980090) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.utils.inc#L82)):_

> ``` SourcePawn
>      * @return array
>      */
>     private function value_format_mapping($keys) {
> ```

Please add a short description of the purpose of this function.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2)_

**Comment by sdp5** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

_[tmgmt_zanata.connector.inc, line 770 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4LPPiNPBvzDjj5KRH:-KJ59deyi5DzFoX9kmlf:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.connector.inc#L770)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> I suggest the name `not_success_response` to be more obvious what it does.
> </details>
> Done.

---

_[tmgmt_zanata.connector.inc, line 777 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4MD2Mxz4dBt0trvYS:-KJ59f510bK7Ne_rpY-C:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.connector.inc#L777)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> This will still only report on one of the response codes. It will be better if we can generate a message or multiple messages that say what was successful and what failed.
> 
> For example, if there is a document that has a success response for the non-html parts but a failure response when it sends "Body" as a html document, there could be 2 messages:
> 
> ``` php
> $job_item->addMessage(
>           'Sent document: non-html strings for item "@title" sent to Zanata as document "@doc_id".',
>           array(...));
> 
> $job_item->addMessage(
>           'Html content "@fieldname" for item "@title" was not successfully sent to Zanata due to ...',
>           array(...), 'error');
> ```
> 
> The message depends on the type of error, like in the current switch statement. The switch statement below could be used if it is included inside a loop over the responses. The return statements would need to be removed, and at the end of the function just return true if all are success (maybe with `return !empty(array_filter($responses, 'test_response_code'));`)
> </details>
> Done.

---

_[tmgmt_zanata.utils.inc, line 82 [r3]](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2#-KJ4FSLhuQMy6ownUTC9:-KJ59gi67zRkyFA_VsVh:-499146009) ([raw file](https://github.com/sundeep-co-in/tmgmt_zanata/blob/7d218bebfdab8a0a12aba37e37ea93fc5e18db48/tmgmt_zanata.utils.inc#L82)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Please add a short description of the purpose of this function.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/sundeep-co-in/tmgmt_zanata/2)_

**Comment by sdp5** [comment]
Please continue with https://github.com/zanata/tmgmt_zanata/pull/8

**Pull request merged**
